# Generated by Django 3.0 on 2019-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/No Activo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activada/No Activada'),
        ),
    ]
