# Generated by Django 3.0 on 2019-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0002_auto_20191205_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Categoría'),
        ),
    ]
