# Generated by Django 3.0 on 2019-12-05 17:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0003_auto_20191205_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.FileField(upload_to='', verbose_name='Ficheros del contrato')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgacionAppVRIP.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgacionAppVRIP.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
                'managed': True,
            },
        ),
    ]
