# Generated by Django 3.0 on 2019-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(upload_to='', verbose_name='Imagen del Post'),
        ),
    ]
