# Generated by Django 3.0 on 2019-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0005_auto_20191205_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='', verbose_name='Imagen del Post'),
        ),
    ]
