# Generated by Django 3.0 on 2019-12-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0006_auto_20191206_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ('-fechaCreacion', '-id'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
