# Generated by Django 3.0 on 2019-12-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0007_auto_20191206_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Autor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.BooleanField(default=False, verbose_name='Publicado/No Publicado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='divulgacionAppVRIP.Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='divulgacionAppVRIP.Post')),
            ],
        ),
    ]
