# Generated by Django 3.0 on 2019-12-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'ordering': ('-fechaCreacion', '-id'), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
