# Generated by Django 3.0 on 2019-12-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0009_auto_20191206_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
