# Generated by Django 3.0 on 2019-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0010_auto_20191206_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
