# Generated by Django 3.0 on 2019-12-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0012_create_default_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ('-fechaCreacion', '-id'), 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
