# Generated by Django 3.0 on 2019-12-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacionAppVRIP', '0013_auto_20191210_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'ordering': ('-fechaCreacion', '-id'), 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
